### ISSUE TITLE
Screen when unregistered users tap a card

### ISSUE THREAD

**Issue by AndrewCLu** [cursive-team/zk-summit#19]
[Designs](https://www.figma.com/file/fxUj5K7DawmhvAT3wRk1X1/ZK-Summit-Design?type=design&node-id=3474%3A25900&mode=design&t=9Ifp6Vi5m6LfauJD-1)
- [x] ideally this actually uses the info returned from the tap to preview what you could have collected

**Comment by rachelaux** [comment]
@AndrewCLu what would there be to preview if the user has not registered?

**Comment by rachelaux** [comment]
designs are [here](https://www.figma.com/file/fxUj5K7DawmhvAT3wRk1X1/ZK-Summit-Design?type=design&node-id=3474%3A25900&mode=design&t=9Ifp6Vi5m6LfauJD-1)
