### ISSUE TITLE
Registration flow

### ISSUE THREAD

**Issue by rachelaux** [cursive-team/zk-summit#22]
https://www.figma.com/file/fxUj5K7DawmhvAT3wRk1X1/ZK-Summit-Design?type=design&node-id=3084%3A14674&mode=design&t=h3Z3QiVWWPzTdA8y-1

**Comment by RiverRuby** [comment]
@kalidiagne we also need this part of the flow
<img width="785" alt="image" src="https://github.com/cursive-team/zk-summit/assets/6290822/349de645-d265-47f0-8893-7735d070979a">
