### ISSUE TITLE
Proofs (page)

### ISSUE THREAD

**Issue by rachelaux** [cursive-team/zk-summit#35]
[Designs are here](https://www.figma.com/file/fxUj5K7DawmhvAT3wRk1X1/ZK-Summit-Design?type=design&node-id=3113%3A19023&mode=design&t=WOS8G9xvG3HzAtGR-1) for the page where users can explore different proofs that they can make.

Updates:
- kept the icons (person and location) to bring life to the page and communicate what is needed for a proof with a visual system
- We could start every title with an emoji to bring some color and differentiation to the cards without creating custom images for each. 
- Card titles should be names rather than directions or actions. Read reasoning [here](https://www.figma.com/file/fxUj5K7DawmhvAT3wRk1X1/ZK-Summit-Design?type=design&node-id=3156%3A6338&mode=design&t=Ho5wo8zKdiOHdUV5-1)

**Comment by RiverRuby** [comment]
To make test proofs to mock this flow:

- make a few accounts by going through login/registration
- check the ids of the users in your DB
  - can connect to postico OR
  - view on vercel: https://vercel.com/cursive/~/stores/postgres/store_0qT5Tvmtdqdm3RWb/data
- go to http://localhost:3000/admin/create_quest
  - make a quest (renamed to proofs)
  - create a requirement to meet some number of users
  - we will only have 1 requirement per quest
