### ISSUE TITLE
Proof Details

### ISSUE THREAD

**Issue by rachelaux** [cursive-team/zk-summit#39]
[Designs](https://www.figma.com/file/fxUj5K7DawmhvAT3wRk1X1/ZK-Summit-Design?type=design&node-id=3146%3A24772&mode=design&t=WOS8G9xvG3HzAtGR-1)

When users clicks on a proof card they will see details that list out what they need to do before they can make the proof. Designs show different text for person vs location requirements. 

When a user completes a proof that only involved **location** requirements, a link will appear [view all] that redirects to their **talk inventory**. Similarly, if a user completes a proof that only involved **person** requirements a link will appear [view all] that redirects to their **contact list**.

**Comment by RiverRuby** [comment]
- [x] When you have 1 sig collected for Symposium seeker quest it takes you to proof completion screen automatically - i think logic for opening the complete quest modal automatically is wrong
- [x] Location icons are wrong
- [x] Icons can sometimes be smaller if the title is very long (try testing with some of the talks in https://www.notion.so/pse-team/Guide-to-testing-ZK-Summit-11-app-b00634516eec47ee837a875fd800af20)
