### ISSUE TITLE
e2e working flow for PSI using websockets

### ISSUE THREAD

**Issue by AndrewCLu** [cursive-team/zk-summit#5]
Functional PSI using websockets

**Comment by RiverRuby** [comment]
- [x] Understand Supabase / realtime
  - [x] Understand architecture of slack app
  - [x] See what changes we need to make to DB/server
- [x] Add back mp_psi
  - [x] Add benchmarks
  - [x] Understand difference with compression
- [x] Add back pkIds  
- [x] Add Supabase messages upon vercel upload
  - [x] Set up anonymous login
  - [x] Set up sign out
  - [x] Update realtimeId on login
  - [x] Add this data to schema
  - [x] Add it upon registration
  - [x] Add API call to update this on new login
- [x] Understand supabase auth
- [x] Move psiRound1Message into vercel blob instead
  - [x] Figure out space usage
  - [x] Determine if compression is necessary
- [x] Add back indexedDB  
- [x] Test pure vercel blobs flow
  - [x] Send psi round 1 message on tap
  - [x] Set up realtime broadcast/presence
  - [x] clean up psi.ts for new flow
  - [x] clean up indexedDB flow
