### ISSUE TITLE
PSI component

### ISSUE THREAD

**Issue by AndrewCLu** [cursive-team/zk-summit#7]
[Designs:](https://www.figma.com/file/fxUj5K7DawmhvAT3wRk1X1/ZK-Summit-Design?type=design&node-id=3156%3A17288&mode=design&t=9Ifp6Vi5m6LfauJD-1)
- [x] Screen 17: make it clear you need to tap at same time
- [x] Screen 17A: progress bar
- [x] Screen 17B: error display (ex: if they aren't with the other person.)
- [x] Screen 18: allow people to do psi multiple times using the [update] button

**Comment by rachelaux** [comment]
I'm making [designs](https://www.figma.com/file/fxUj5K7DawmhvAT3wRk1X1/ZK-Summit-Design?type=design&node-id=3462%3A23500&mode=design&t=9Ifp6Vi5m6LfauJD-1) in response to your notes @AndrewCLu 
cc: @RiverRuby
